$ErrorActionPreference='Stop'
$root=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;$requestSchema=Join-Path $root 'review\contracts\hirc-request-case.candidate.schema.v2.json';$transferSchema=Join-Path $root 'review\contracts\hirc-transfer-case.candidate.schema.json';$requestFixture=Get-Content -Raw (Join-Path $root 'review\fixtures\security-request-state-cases-v1.json')|ConvertFrom-Json;$transferFixture=Get-Content -Raw (Join-Path $root 'review\fixtures\security-transfer-state-cases-v1.json')|ConvertFrom-Json;$casePath=Join-Path $root 'review\fixtures\security-privacy-dataflow-cases-v1.json';$caseManifest=Get-Content -Raw $casePath|ConvertFrom-Json;$output=Join-Path $root 'review\fixtures\security-privacy-dataflow-validation-v1.json'
$bindingResults=foreach($b in $caseManifest.bindings){$p=Join-Path $root $b.path;$x=Get-Item $p;[pscustomobject]@{path=$b.path;sha256=(Get-FileHash $p -Algorithm SHA256).Hash.ToLower();bytes=$x.Length;pass=((Get-FileHash $p -Algorithm SHA256).Hash.ToLower()-eq$b.sha256-and$x.Length-eq$b.bytes)}}
$expectedPositive=@('current_consent_request','privacy_bound_effect','encrypted_transfer','legitimate_audience_attenuation');$expectedAdverse=@('stale_request_consent','empty_request_audience','missing_request_retention','missing_derived_policy','effect_missing_privacy_snapshot','transfer_missing_consent','transfer_missing_encryption','transfer_missing_deletion_residual','request_audience_widened_after_preview','request_purpose_changed_after_preview','transfer_audience_widened','transfer_derived_policy_changed','transfer_retention_changed','transfer_encryption_downgraded','transfer_residual_erased');$catalogPass=((Compare-Object @($caseManifest.positive|Sort-Object) @($expectedPositive|Sort-Object)).Count -eq 0 -and (Compare-Object @($caseManifest.adverse|Sort-Object) @($expectedAdverse|Sort-Object)).Count -eq 0)
function Clone($x){return($x|ConvertTo-Json -Depth 50|ConvertFrom-Json)}
function Text-Sha($text){$a=[Security.Cryptography.SHA256]::Create();try{return [Convert]::ToHexString($a.ComputeHash([Text.Encoding]::UTF8.GetBytes($text))).ToLower()}finally{$a.Dispose()}}
function Request-PrivacySha($p){$o=[ordered]@{data_classes=@($p.data_classes);audience_refs=@($p.audience_refs);purpose_ref=$p.purpose_ref;consent_snapshot_ref=$p.consent_snapshot_ref;consent_current=[bool]$p.consent_current;retention_policy_ref=$p.retention_policy_ref;derived_data_policy_ref=$p.derived_data_policy_ref;egress_policy_ref=$p.egress_policy_ref;deletion_residual_ref=$p.deletion_residual_ref;encryption_required=[bool]$p.encryption_required};return Text-Sha ($o|ConvertTo-Json -Compress)}
function Transfer-PrivacySha($p){$o=[ordered]@{purpose_ref=$p.purpose_ref;audience_refs=@($p.audience_refs);data_classes=@($p.data_classes);consent_snapshot_refs=@($p.consent_snapshot_refs);retention_policy_ref=$p.retention_policy_ref;derived_data_policy_ref=$p.derived_data_policy_ref;egress_policy_ref=$p.egress_policy_ref;encryption_profile_ref=$p.encryption_profile_ref;deletion_residual_ref=$p.deletion_residual_ref};return Text-Sha ($o|ConvertTo-Json -Compress)}
function Same-Set($a,$b){return (Compare-Object @($a|Sort-Object) @($b|Sort-Object)).Count -eq 0}
function Relation-Valid($p){$s=$p.source_privacy;$q=$p.privacy_relation;$audienceSame=Same-Set $p.audience_refs $s.audience_refs;if($audienceSame){if($q.audience -ne 'EQUAL'){return $false}}else{if($q.audience -ne 'NARROWER'){return $false};foreach($a in $p.audience_refs){if($a -notin $s.audience_refs){return $false}}};$checks=@(@('data_classes','data_class','STRONGER'),@('consent_snapshot_refs','consent','CURRENT_RECONSENTED'),@('purpose_ref','purpose','NARROWER'),@('retention_policy_ref','retention','SHORTER'),@('derived_data_policy_ref','derived_data','MORE_RESTRICTIVE'),@('egress_policy_ref','egress','MORE_RESTRICTIVE'),@('encryption_profile_ref','encryption','STRONGER'),@('deletion_residual_ref','deletion_residual','MORE_EXPLICIT'));foreach($c in $checks){$field=$c[0];$relation=$c[1];$allowed=$c[2];$same=if($p.$field -is [array]){Same-Set $p.$field $s.$field}else{$p.$field -eq $s.$field};if($same){if($q.$relation -ne 'EQUAL'){return $false}}else{if($q.$relation -ne $allowed){return $false}}};return $true}
function Req($r){$structural=Test-Json -Json ($r|ConvertTo-Json -Depth 50) -SchemaFile $requestSchema -ErrorAction SilentlyContinue;if(-not$structural){return $false};if($r.effect){return $r.effect.privacy_snapshot_sha256 -eq (Request-PrivacySha $r.privacy)};return $true}
function Transfer($r){$r2=Clone $transferFixture.base;$r2.state='ACCEPTED';$r2|Add-Member freeze (Clone $transferFixture.freeze);$r2|Add-Member package $r;$r2|Add-Member acceptance (Clone $transferFixture.acceptance);$structural=Test-Json -Json ($r2|ConvertTo-Json -Depth 50) -SchemaFile $transferSchema -ErrorAction SilentlyContinue;if(-not$structural){return $false};if($r.source_privacy_snapshot_sha256 -ne (Transfer-PrivacySha $r.source_privacy)){return $false};if($r.privacy_snapshot_sha256 -ne (Transfer-PrivacySha $r)){return $false};return (Relation-Valid $r)}
$attenuated=Clone $transferFixture.package;$attenuated.source_privacy.audience_refs += 'audience:external';$attenuated.source_privacy_snapshot_sha256=(Transfer-PrivacySha $attenuated.source_privacy);$attenuated.privacy_relation.audience='NARROWER'
$positive=@([pscustomobject]@{name='current_consent_request';accepted=(Req (Clone $requestFixture.bases.analysis))},[pscustomobject]@{name='privacy_bound_effect';accepted=(Req (Clone $requestFixture.bases.performed))},[pscustomobject]@{name='encrypted_transfer';accepted=(Transfer (Clone $transferFixture.package))},[pscustomobject]@{name='legitimate_audience_attenuation';accepted=(Transfer $attenuated)})
$cases=@();function Bad($name,$accepted){$script:cases+=[pscustomobject]@{name=$name;rejected=(-not$accepted)}}
$r=Clone $requestFixture.bases.performed;$r.privacy.consent_current=$false;Bad 'stale_request_consent' (Req $r)
$r=Clone $requestFixture.bases.performed;$r.privacy.audience_refs=@();Bad 'empty_request_audience' (Req $r)
$r=Clone $requestFixture.bases.performed;$r.privacy.PSObject.Properties.Remove('retention_policy_ref');Bad 'missing_request_retention' (Req $r)
$r=Clone $requestFixture.bases.performed;$r.privacy.PSObject.Properties.Remove('derived_data_policy_ref');Bad 'missing_derived_policy' (Req $r)
$r=Clone $requestFixture.bases.performed;$r.effect.PSObject.Properties.Remove('privacy_snapshot_ref');Bad 'effect_missing_privacy_snapshot' (Req $r)
$p=Clone $transferFixture.package;$p.consent_snapshot_refs=@();Bad 'transfer_missing_consent' (Transfer $p)
$p=Clone $transferFixture.package;$p.PSObject.Properties.Remove('encryption_profile_ref');Bad 'transfer_missing_encryption' (Transfer $p)
$p=Clone $transferFixture.package;$p.PSObject.Properties.Remove('deletion_residual_ref');Bad 'transfer_missing_deletion_residual' (Transfer $p)
$r=Clone $requestFixture.bases.performed;$r.privacy.audience_refs += 'audience:external';Bad 'request_audience_widened_after_preview' (Req $r)
$r=Clone $requestFixture.bases.performed;$r.privacy.purpose_ref='purpose:other';Bad 'request_purpose_changed_after_preview' (Req $r)
$p=Clone $transferFixture.package;$p.audience_refs += 'audience:external';$p.privacy_snapshot_sha256=(Transfer-PrivacySha $p);Bad 'transfer_audience_widened' (Transfer $p)
$p=Clone $transferFixture.package;$p.derived_data_policy_ref='derived:declassified';$p.privacy_snapshot_sha256=(Transfer-PrivacySha $p);Bad 'transfer_derived_policy_changed' (Transfer $p)
$p=Clone $transferFixture.package;$p.retention_policy_ref='retention:longer';$p.privacy_snapshot_sha256=(Transfer-PrivacySha $p);Bad 'transfer_retention_changed' (Transfer $p)
$p=Clone $transferFixture.package;$p.encryption_profile_ref='encryption:none';$p.privacy_snapshot_sha256=(Transfer-PrivacySha $p);Bad 'transfer_encryption_downgraded' (Transfer $p)
$p=Clone $transferFixture.package;$p.deletion_residual_ref='residual:none';$p.privacy_snapshot_sha256=(Transfer-PrivacySha $p);Bad 'transfer_residual_erased' (Transfer $p)
$state=if($catalogPass -and ($bindingResults|Where-Object{-not$_.pass}).Count -eq 0 -and ($positive|Where-Object{-not$_.accepted}).Count -eq 0 -and ($cases|Where-Object{-not$_.rejected}).Count -eq 0){'PASS'}else{'FAIL'};$result=[pscustomobject]@{schema='hirc.security-privacy-dataflow-validation/1';state=$state;bindings=$bindingResults;catalog=[pscustomobject]@{schema=$caseManifest.schema;positive_labels_match=$catalogPass;positive_count=@($caseManifest.positive).Count;adverse_count=@($caseManifest.adverse).Count};request_schema_sha256=(Get-FileHash $requestSchema -Algorithm SHA256).Hash.ToLower();transfer_schema_sha256=(Get-FileHash $transferSchema -Algorithm SHA256).Hash.ToLower();case_manifest_sha256=(Get-FileHash $casePath -Algorithm SHA256).Hash.ToLower();positive=$positive;adverse=$cases;ordinal_prior_frame_correction='Prior peer result remains exact evidence for its old pins; this R006 catalog-alignment wrapper and later packet require current non-MBV audit/review.';nonclaim='Current-record privacy/dataflow binding and typed attenuation validation only; trusted prior-preview/source resolution, actual consent, encryption, deletion, privacy engineering, runtime enforcement and S014 acceptance remain separate.'};$out=$result|ConvertTo-Json -Depth 10;[IO.File]::WriteAllText($output,$out+"`n",[Text.UTF8Encoding]::new($false));$out;if($state-ne'PASS'){exit 1}
